### ISSUE TITLE
マウスモードからメニュー触ると死ぬ?

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#111]
マウスモードに入ってから、F10(ウィンドウマネージャにもよる?)で
メニューバーのメニューを開いて何か押すと死ぬ。

```
./src/common/wincmn.cpp(3346): assert "Assert failure" failed in
DoNotifyWindowAboutCaptureLost(): window that captured the mouse
didn't process wxEVT_MOUSE_CAPTURE_LOST

(nono:1994): Gtk-WARNING **: 13:34:08.534: gtk_window_set_titlebar()
called on a realized window
Trace/BPT trap (core dumped)
```

backtrace
```
#0  0x0000758c9fb67c3a in _lwp_kill () from /usr/lib/libc.so.12
#1  0x0000758ca0890c03 in ?? () from /usr/pkg/lib/libwx_baseu-3.0.so.0
#2  0x0000758ca088f55f in wxOnAssert(char const*, int, char const*, char const*, wchar_t const*) () from /usr/pkg/lib/libwx_baseu-3.0.so.0
#3  0x0000758ca1a45cce in wxWindowBase::ReleaseMouse() ()
   from /usr/pkg/lib/libwx_gtk3u_core-3.0.so.0
#4  0x0000000000428757 in WXMainView::SetMouseMode (this=0x758ca375ca00,
    mode=<optimized out>) at wxmainview.cpp:222
#5  0x0000758ca09d61ad in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#6  0x0000758ca09d651f in wxEvtHandler::SearchDynamicEventTable(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#7  0x0000758ca09d65a1 in wxEvtHandler::TryHereOnly(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#8  0x0000758ca09d6635 in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#9  0x0000758ca09d6686 in wxEvtHandler::ProcessEvent(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#10 0x0000758ca09d6433 in wxEvtHandler::SafelyProcessEvent(wxEvent&) ()
   from /usr/pkg/lib/libwx_baseu-3.0.so.0
#11 0x0000758ca18aa95a in ?? () from /usr/pkg/lib/libwx_gtk3u_core-3.0.so.0
#12 0x0000758c9eb89c0f in _gtk_marshal_BOOLEAN__BOXED ()
   from /usr/pkg/lib/libgtk-3.so.0
#13 0x0000758c9c012ab0 in g_closure_invoke ()
   from /usr/pkg/lib/libgobject-2.0.so.0
#14 0x0000758c9c024046 in signal_emit_unlocked_R ()
   from /usr/pkg/lib/libgobject-2.0.so.0
👍 :
```

**Comment by isaki68k** [comment]
0c7c0a8f (2022-05-24) で修正。
